name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *' # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate snake game
      uses: Platane/snk@master
      with:
        github_user_name: GuilhermeVieira-code 
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
